sensi_yaml_gui_edit:
    pattern: /edit/{configFile}
    defaults: { _controller: SensiYamlGuiBundle:Default:edit }
    
sensi_yaml_gui_list:
    pattern: /list
    defaults: { _controller: SensiYamlGuiBundle:Default:list }